/* Generated by AN DISI Unibo */ 
package it.unibo.clientparkinmock

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Clientparkinmock ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "initstate"
	}
	@kotlinx.coroutines.ObsoleteCoroutinesApi
	@kotlinx.coroutines.ExperimentalCoroutinesApi			
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		  
				val ACTORNAME = "clientparkinmock"
				var SLOTNUM = 0 
				var TOKENID = ""
				
		return { //this:ActionBasciFsm
				state("initstate") { //this:State
					action { //it:State
						println("$ACTORNAME : Enter initstate")
					}
					 transition( edgeName="goto",targetState="sendcarrequest", cond=doswitch() )
				}	 
				state("sendcarrequest") { //this:State
					action { //it:State
						println("$ACTORNAME : Enter sendcarrequest")
						request("carrequest", "carrequest(X)" ,"parkmanagerservice" )  
					}
					 transition(edgeName="t00",targetState="sendparkrequeststate",cond=whenReply("informin"))
				}	 
				state("sendparkrequeststate") { //this:State
					action { //it:State
						println("$ACTORNAME : Enter parkrequeststate")
						if( checkMsgContent( Term.createTerm("informin(SLOTNUM)"), Term.createTerm("informin(SLOTNUM)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 SLOTNUM = payloadArg(0).toInt()  
								println("$ACTORNAME : SLOTNUM = $SLOTNUM ")
						}
						request("parkrequest", "parkrequest(X)" ,"parkmanagerservice" )  
					}
					 transition(edgeName="t01",targetState="endstate",cond=whenReply("receipt"))
				}	 
				state("endstate") { //this:State
					action { //it:State
						println("Enter watiforcarenter_ext_state")
						if( checkMsgContent( Term.createTerm("receipt(TOKENID)"), Term.createTerm("receipt(TOKENID)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 TOKENID = payloadArg(0).toString()  
						}
						println("$ACTORNAME : TOKENID = $TOKENID ")
					}
				}	 
			}
		}
}
