/* Generated by AN DISI Unibo */ 
package it.unibo.clientparkouttest

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Clientparkouttest ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "initState"
	}
	@kotlinx.coroutines.ObsoleteCoroutinesApi
	@kotlinx.coroutines.ExperimentalCoroutinesApi			
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		 var TOKENID = ""  
		return { //this:ActionBasciFsm
				state("initState") { //this:State
					action { //it:State
						println("Enter initState")
					}
					 transition( edgeName="goto",targetState="waitforpickupok_ext", cond=doswitch() )
				}	 
				state("waitforpickupok_ext") { //this:State
					action { //it:State
						println("Enter wait")
						request("pickup_ext", "TOKENID" ,"clientparkout" )  
					}
					 transition(edgeName="t08",targetState="waitfor_upload",cond=whenReply("pickupok_ext"))
				}	 
				state("waitfor_upload") { //this:State
					action { //it:State
						println("Enter waitfor_upload")
					}
				}	 
			}
		}
}
