/* Generated by AN DISI Unibo */ 
package it.unibo.ctxclientparkin
import it.unibo.kactor.QakContext
import it.unibo.kactor.sysUtil
import kotlinx.coroutines.runBlocking

fun main() = runBlocking {
	QakContext.createContexts(
<<<<<<< HEAD
	        "localhost", this, "parkingmanagerservicesystem.pl", "sysRules.pl"
=======
	        "localhost", this, "parkingmanagerservice.pl", "sysRules.pl"
>>>>>>> af09b0e18824afe27c3b10302383b32993892f66
	)
}

