/* Generated by AN DISI Unibo */ 
package it.unibo.ctxclientguiparkout
import it.unibo.kactor.QakContext
import it.unibo.kactor.sysUtil
import kotlinx.coroutines.runBlocking

fun main() = runBlocking {
	QakContext.createContexts(
	        "localhost\\ctxclientguiparkout", this, "parkingmanagerservice.pl", "sysRules.pl"
	)
}

