/* Generated by AN DISI Unibo */ 
package it.unibo.ctxclientparkinmock
import it.unibo.kactor.QakContext
import it.unibo.kactor.sysUtil
import kotlinx.coroutines.runBlocking

fun main() = runBlocking {
	QakContext.createContexts(
	        "localhost", this, "parkmanagerservice.pl", "sysRules.pl"
	)
}

